# Generated by Django 4.2.1 on 2023-06-07 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_active_active_display_active_offline_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_msg',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user_msg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 7, 19, 25, 26, 892475)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 7, 19, 25, 26, 892475)),
        ),
    ]
